name: Build Acode

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Cordova globally
      run: npm install -g cordova@12.0.0
    
    - name: Install dependencies and setup
      run: npm run setup

    - name: Setup Android signing
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android-signing-key.jks
        echo "storeFile=../../../android-signing-key.jks" >> platforms/android/release-signing.properties
        echo "storeType=jks" >> platforms/android/release-signing.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> platforms/android/release-signing.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> platforms/android/release-signing.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> platforms/android/release-signing.properties 
    
    - name: Build application (paid version, production)
      run: npm run build android paid p
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: acode-paid-release-apk
        path: platforms/android/app/build/outputs/apk/debug/*.apk
